<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit719fbba6ea5d0fb441937e666c08ee78
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Facebook\\WebDriver\\' => 19,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Facebook\\WebDriver\\' => 
        array (
            0 => __DIR__ . '/..' . '/facebook/webdriver/lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit719fbba6ea5d0fb441937e666c08ee78::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit719fbba6ea5d0fb441937e666c08ee78::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
